[tools]
bat = "latest"
claude = "latest"
go = "1.25.3"

[tasks.build]
run = "mkdir -p ../dist && go build -buildvcs=false -o ../dist/agentjail ."
dir = "cli"

[tasks.build_win]
run = "mkdir ../dist --force && go build -o ../dist/agentjail.exe ."
dir = "cli"

[tasks.test]
run = "go test ./... -v"
dir = "cli"

[tasks.run]
run = "go run ."
dir = "cli"
