#:schema https://raw.githubusercontent.com/NSPC911/rovr/refs/tags/v0.7.0.dev3/src/rovr/config/schema.json
[interface]
use_reactive_layout = true
show_hidden_files = true
image_protocol = "Auto"
[interface.compact_mode]
buttons = false
panels = true

[settings.editor]
open_all_in_editor = false

[settings.editor.file]
run = "micro"
block = false
suspend = true

[settings.editor.folder]
run = "micro"
block = false
suspend = true

[theme]
default = "flexoki"

transparent = false

[keybinds]
toggle_pin = ["P"]
toggle_pinned_sidebar = ["S"]
toggle_preview_sidebar = ["I"]
toggle_footer = ["F"]
toggle_menuwrapper = ["M"]
focus_toggle_pinned_sidebar = ["s"]
focus_file_list = ["escape"]
focus_toggle_preview_sidebar = ["i"]
focus_toggle_path_switcher = ["ctrl+l"]
focus_search = ["ctrl+f"]
focus_toggle_processes = ["p"]
focus_toggle_clipboard = ["c"]
focus_toggle_metadata = ["m"]
copy = ["ctrl+c"]
paste = ["ctrl+v"]
cut = ["ctrl+x"]
delete = ["delete"]
rename = ["f2"]
new = ["ctrl+n"]
zip = ["alt+z"]
unzip = ["alt+x"]
up = ["up"]
down = ["down"]
up_tree = ["left", "alt+up"]
down_tree = ["right", "enter"]
page_up = ["pageup"]
page_down = ["pagedown"]
home = ["home"]
end = ["end"]
hist_previous = ["backspace", "alt+left"]
hist_next = ["alt+right"]
toggle_all = ["ctrl+a"]
toggle_visual = ["ctrl+space"]
toggle_hidden_files = ["."]
select_up = ["shift+up"]
select_down = ["shift+down"]
select_page_up = ["shift+pageup"]
select_page_down = ["shift+pagedown"]
select_home = ["shift+home"]
select_end = ["shift+end"]
tab_next = ["ctrl+left_square_brace"]
tab_previous = ["ctrl+right_square_brace"]
tab_new = ["ctrl+t"]
tab_close = ["ctrl+w"]
preview_scroll_left = ["left"]
preview_scroll_right = ["right"]
show_keybinds = ["f1"]
quit_app = ["ctrl+q","alt+q"]
command_palette = "ctrl+p"
suspend_app = ["ctrl+z"]
open_editor = ["ctrl+e"]

[keybinds.extra_copy]
open_popup = ["C"]
copy_to_rovr = ["r"]
copy_single_path = ["p"]
copy_to_system_clip = ["s"]
copy_current_directory = ["u"]

[keybinds.change_sort_order]
open_popup = ["o"]
name = ["a"]
extension = ["e"]
natural = ["n"]
size = ["s"]
created = ["c"]
modified = ["m"]
descending = ["d"]

[keybinds.delete_files]
trash = ["d"]
delete = ["shift+d"]
cancel = ["escape"]

[keybinds.filename_conflict]
overwrite = ["o"]
skip = ["s"]
rename = ["r"]
cancel = ["escape"]
dont_ask_again = ["a"]

[keybinds.file_in_use]
retry = ["r"]
skip = ["s"]
cancel = ["escape"]
dont_ask_again = ["a"]

[keybinds.filter_modal]
exit = ["escape"]
down = ["down"]
up = ["up"]

[keybinds.yes_or_no]
yes = ["y", "enter"]
no = ["n", "escape"]
dont_ask_again = ["a"]

[plugins.rg]
enabled = true
keybinds = ['\\']

[plugins.fd]
enabled = true
keybinds = ['ctrl+g']

[plugins.bat]
enabled = true

[plugins.zoxide]
enabled = true
keybinds = ['ctrl+d']

[plugins.poppler]
enabled = true

[plugins.file_one]
enabled = true